sem 3, homework 3, task 1
spp-plotnikov/homeworks pull request #26
Opened 2016-11-07 01:23 UTC by spp-plotnikov

2016-11-07 20:41 UTC, jzuken requested changes
ну а так в целом вполне норм

2016-11-07 20:41 UTC, jzuken commented on 3sem/hw3/Logic_Component/cannon.cpp
> +    delete shotMaker;
вот тут падает при выходе. ты его два раза не удаляешь случаем?

2016-11-07 20:41 UTC, jzuken commented on 3sem/hw3/Logic_Component/game.cpp
> +    landscape << QPoint(0, realHeight)
было бы круто грузить его из файла

2016-11-07 20:41 UTC, jzuken commented on 3sem/hw3/Logic_Component/cannon.h
> +    enum CannonColour {Black, Blue, Gray, Orange, Purple, Red};
по стайлгайду значения енума должны именоваться как обычные переменные

2016-11-07 20:41 UTC, jzuken commented on 3sem/hw3/Logic_Component/cannon.cpp
> +    delete itemInScene;
этого товарища сцена сама удалит, а она сама удалит пульку, если оно LittleBulletShot

2016-11-07 20:41 UTC, jzuken commented on 3sem/hw3/Logic_Component/littlebulletshot.h
> +    // phisical items:
physical

2016-11-08 02:18 UTC, spp-plotnikov commented on 3sem/hw3/Logic_Component/game.cpp
> +    landscape << QPoint(0, realHeight)
Переделал :-) Просто по условию задачи 3.1 вы разрешили захардкодить ландшафт, вот я и подумал

2016-11-08 02:21 UTC, spp-plotnikov commented on 3sem/hw3/Logic_Component/cannon.h
> +    enum CannonColour {Black, Blue, Gray, Orange, Purple, Red};
Переделал :-) Просто здесь вроде не было про это: http://se.math.spbu.ru/SE/Members/ylitvinov/styleguide

2016-11-08 02:23 UTC, spp-plotnikov commented on 3sem/hw3/Logic_Component/littlebulletshot.h
> +    // phisical items:
Исправил :-) Моя голова заслуживает удар словарём :-)

2016-11-08 20:39 UTC, jzuken commented on 3sem/hw3/Logic_Component/game.cpp
> +    landscape << QPoint(0, realHeight)
да, я понимаю, но круто же из файла читать :)

2016-11-08 20:40 UTC, merged